export interface ConvoyWaypoint {
  lat: number;
  lng: number;
  name: string;
  elevationMeters: number;
}

export interface ConvoyDefinition {
  id: string;
  name: string;
  agency: string;
  cargo: string;
  weightTons: number;
  vehicleType: string;
  primaryPath: ConvoyWaypoint[];
  alternatePath?: ConvoyWaypoint[];
  hazardZone: {
    lat: number;
    lng: number;
    radiusMeters: number;
    name: string;
    hazardType: string;
  };
}

export const SIMULATED_CONVOYS: ConvoyDefinition[] = [
  {
    id: "convoy-alpha",
    name: "Convoy Alpha (Medical & Oxygen Relief)",
    agency: "MDoNER · NDRF Logistics",
    cargo: "Medical Oxygen & Critical Surgical Kits",
    weightTons: 14.5,
    vehicleType: "Heavy All-Terrain Ashok Leyland 4x4",
    hazardZone: {
      lat: 25.18,
      lng: 92.35,
      radiusMeters: 14000,
      name: "Sonapur Mudslide Defile (NH-6 Sector)",
      hazardType: "Active Monsoon Flash Mudflow",
    },
    primaryPath: [
      { lat: 26.185, lng: 91.75, name: "Guwahati Central Depot", elevationMeters: 55 },
      { lat: 26.14, lng: 91.8, name: "Dispur Regional Command", elevationMeters: 62 },
      { lat: 26.06, lng: 91.88, name: "Jorabat Strategic Junction", elevationMeters: 110 },
      { lat: 25.9, lng: 91.88, name: "Nongpoh Valley Post", elevationMeters: 590 },
      { lat: 25.68, lng: 91.9, name: "Umiam Lake Pass", elevationMeters: 1020 },
      { lat: 25.578, lng: 91.893, name: "Shillong Civil Hospital", elevationMeters: 1520 },
      { lat: 25.44, lng: 92.2, name: "Jowai Ridge Corridor", elevationMeters: 1380 },
      { lat: 25.18, lng: 92.35, name: "Sonapur Hazard Sector", elevationMeters: 420 },
      { lat: 24.95, lng: 92.6, name: "Badarpur Railhead", elevationMeters: 45 },
      { lat: 24.833, lng: 92.779, name: "Silchar Valley Disaster Camp", elevationMeters: 28 },
    ],
    alternatePath: [
      { lat: 25.578, lng: 91.893, name: "Shillong Civil Hospital", elevationMeters: 1520 },
      { lat: 25.48, lng: 92.55, name: "Umrangso Hydro Bypass", elevationMeters: 840 },
      { lat: 25.17, lng: 92.75, name: "Haflong Valley Ridge", elevationMeters: 680 },
      { lat: 24.833, lng: 92.779, name: "Silchar Valley Disaster Camp", elevationMeters: 28 },
    ],
  },
  {
    id: "convoy-bravo",
    name: "Convoy Bravo (BRO Heavy Excavator Column)",
    agency: "Border Roads Organisation (BRO)",
    cargo: "Hydraulic Breakers & Caterpillar Bulldozer",
    weightTons: 38.0,
    vehicleType: "BEML Tatra 8x8 Recovery Column",
    hazardZone: {
      lat: 27.505,
      lng: 92.103,
      radiusMeters: 12000,
      name: "Sela Pass North Wall (Elevation 4,170m)",
      hazardType: "Catastrophic Rockfall & Permafrost Slip",
    },
    primaryPath: [
      { lat: 26.65, lng: 92.79, name: "Tezpur BRO Main Base", elevationMeters: 75 },
      { lat: 27.01, lng: 92.65, name: "Bhalukpong Inner Line Gate", elevationMeters: 213 },
      { lat: 27.18, lng: 92.52, name: "Tenga Valley Military Station", elevationMeters: 1260 },
      { lat: 27.264, lng: 92.423, name: "Bomdila Pass Peak", elevationMeters: 2415 },
      { lat: 27.35, lng: 92.24, name: "Dirang Hydro Basin", elevationMeters: 1560 },
      { lat: 27.45, lng: 92.15, name: "Baisakhi High Camp", elevationMeters: 3100 },
      { lat: 27.505, lng: 92.103, name: "Sela Pass Ridge (High Risk)", elevationMeters: 4170 },
      { lat: 27.58, lng: 91.86, name: "Tawang Forward Logistics Depot", elevationMeters: 3048 },
    ],
    alternatePath: [
      { lat: 26.65, lng: 92.79, name: "Tezpur BRO Main Base", elevationMeters: 75 },
      { lat: 27.01, lng: 92.65, name: "Bhalukpong Inner Line Gate", elevationMeters: 213 },
      { lat: 27.18, lng: 92.52, name: "Tenga Valley Military Station", elevationMeters: 1260 },
      { lat: 27.264, lng: 92.423, name: "Bomdila Pass Peak", elevationMeters: 2415 },
      { lat: 27.32, lng: 92.35, name: "Sangti Valley Strategic Bypass", elevationMeters: 1780 },
      { lat: 27.42, lng: 92.20, name: "Dirang-Tawang Tactical Tunnel Bypass", elevationMeters: 2200 },
      { lat: 27.58, lng: 91.86, name: "Tawang Forward Logistics Depot", elevationMeters: 3048 },
    ],
  },
  {
    id: "convoy-charlie",
    name: "Convoy Charlie (NDRF Emergency Ration Fleet)",
    agency: "National Disaster Response Force (NDRF)",
    cargo: "Ready-To-Eat Rations & Water Purification Units",
    weightTons: 22.0,
    vehicleType: "Tata LPTA 715 4x4 Quick-Response Fleet",
    hazardZone: {
      lat: 25.5,
      lng: 94.15,
      radiusMeters: 15000,
      name: "Mao Gate Inter-State Mountain Slump",
      hazardType: "Torrential Debris Flow Blockage",
    },
    primaryPath: [
      { lat: 25.906, lng: 93.727, name: "Dimapur Railway Supply Yard", elevationMeters: 145 },
      { lat: 25.79, lng: 93.77, name: "Chumukedima Defile Checkpost", elevationMeters: 240 },
      { lat: 25.67, lng: 94.108, name: "Kohima Highland Command", elevationMeters: 1444 },
      { lat: 25.5, lng: 94.15, name: "Mao Border Pass", elevationMeters: 1820 },
      { lat: 25.26, lng: 94.02, name: "Senapati Relief Center", elevationMeters: 1040 },
      { lat: 25.01, lng: 93.95, name: "Kangpokpi Medical Post", elevationMeters: 920 },
      { lat: 24.817, lng: 93.936, name: "Imphal Kangla Command Camp", elevationMeters: 786 },
    ],
  },
];

/** Calculate distance in meters between two lat/lng pairs */
export function getDistanceMeters(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371e3;
  const φ1 = (lat1 * Math.PI) / 180;
  const φ2 = (lat2 * Math.PI) / 180;
  const Δφ = ((lat2 - lat1) * Math.PI) / 180;
  const Δλ = ((lon2 - lon1) * Math.PI) / 180;

  const a =
    Math.sin(Δφ / 2) * Math.sin(Δφ / 2) +
    Math.cos(φ1) * Math.cos(φ2) * Math.sin(Δλ / 2) * Math.sin(Δλ / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

  return R * c;
}

/** Interpolate position along waypoint array based on progress 0..1 */
export function interpolateConvoyPosition(
  waypoints: ConvoyWaypoint[],
  progress: number,
): { lat: number; lng: number; heading: number; currentWaypoint: string; elevation: number } {
  if (!waypoints || waypoints.length === 0) {
    return { lat: 0, lng: 0, heading: 0, currentWaypoint: "Unknown", elevation: 0 };
  }
  if (waypoints.length === 1 || progress <= 0) {
    return {
      lat: waypoints[0].lat,
      lng: waypoints[0].lng,
      heading: 0,
      currentWaypoint: waypoints[0].name,
      elevation: waypoints[0].elevationMeters,
    };
  }
  if (progress >= 1) {
    const last = waypoints[waypoints.length - 1];
    return {
      lat: last.lat,
      lng: last.lng,
      heading: 0,
      currentWaypoint: last.name,
      elevation: last.elevationMeters,
    };
  }

  // Calculate total path distance
  const segmentDistances: number[] = [];
  let totalDist = 0;
  for (let i = 0; i < waypoints.length - 1; i++) {
    const d = getDistanceMeters(
      waypoints[i].lat,
      waypoints[i].lng,
      waypoints[i + 1].lat,
      waypoints[i + 1].lng,
    );
    segmentDistances.push(d);
    totalDist += d;
  }

  const targetDist = progress * totalDist;
  let accumulated = 0;

  for (let i = 0; i < segmentDistances.length; i++) {
    const nextAcc = accumulated + segmentDistances[i];
    if (targetDist <= nextAcc || i === segmentDistances.length - 1) {
      const segRatio = (targetDist - accumulated) / (segmentDistances[i] || 1);
      const clampedRatio = Math.max(0, Math.min(1, segRatio));

      const p1 = waypoints[i];
      const p2 = waypoints[i + 1];

      const lat = p1.lat + (p2.lat - p1.lat) * clampedRatio;
      const lng = p1.lng + (p2.lng - p1.lng) * clampedRatio;
      const elevation = Math.round(
        p1.elevationMeters + (p2.elevationMeters - p1.elevationMeters) * clampedRatio,
      );

      // Calculate heading angle
      const dLng = ((p2.lng - p1.lng) * Math.PI) / 180;
      const y = Math.sin(dLng) * Math.cos((p2.lat * Math.PI) / 180);
      const x =
        Math.cos((p1.lat * Math.PI) / 180) * Math.sin((p2.lat * Math.PI) / 180) -
        Math.sin((p1.lat * Math.PI) / 180) *
          Math.cos((p2.lat * Math.PI) / 180) *
          Math.cos(dLng);
      const heading = ((Math.atan2(y, x) * 180) / Math.PI + 360) % 360;

      return {
        lat,
        lng,
        heading,
        currentWaypoint: `${p1.name} ➔ ${p2.name}`,
        elevation,
      };
    }
    accumulated = nextAcc;
  }

  const fallback = waypoints[waypoints.length - 1];
  return {
    lat: fallback.lat,
    lng: fallback.lng,
    heading: 0,
    currentWaypoint: fallback.name,
    elevation: fallback.elevationMeters,
  };
}

export type FleetCategory = "medical" | "food" | "fuel" | "machinery";

export interface ConvoyFleetItem {
  id: string; // e.g. "CV-01", "CV-04", etc.
  callsign: string;
  category: FleetCategory;
  agency: string;
  origin: string;
  destination: string;
  cargoDesc: string;
  weightMT: number;
  status: "en_route" | "diverted" | "delayed" | "staging" | "delivered";
  corridor: string;
  vehicleType: string;
  eta: string;
  activeSector: string;
  lat: number;
  lng: number;
  impactedByHazard?: string;
  elevationMeters: number;
}

export const FLEET_CATEGORIES: { id: FleetCategory; label: string; count: number; cargoMT: number; color: string; icon: string }[] = [
  { id: "medical", label: "Medical & Trauma", count: 12, cargoMT: 118, color: "text-emerald-400 bg-emerald-950/40 border-emerald-500/50", icon: "🚑" },
  { id: "food", label: "Food & Rations", count: 18, cargoMT: 240, color: "text-amber-400 bg-amber-950/40 border-amber-500/50", icon: "🌾" },
  { id: "fuel", label: "Fuel & POL", count: 7, cargoMT: 180, color: "text-orange-400 bg-orange-950/40 border-orange-500/50", icon: "⛽" },
  { id: "machinery", label: "Heavy Machinery", count: 5, cargoMT: 90, color: "text-cyan-400 bg-cyan-950/40 border-cyan-500/50", icon: "🚜" },
];

export const FLEET_CONVOYS: ConvoyFleetItem[] = [
  // Medical Convoys (12)
  {
    id: "CV-01",
    callsign: "MED-ALPHA-01",
    category: "medical",
    agency: "NDRF 1st Bn",
    origin: "Guwahati Depot",
    destination: "Silchar Medical College",
    cargoDesc: "ICU Ventilators & Blood Plasma",
    weightMT: 9.5,
    status: "en_route",
    corridor: "NH-6",
    vehicleType: "Ashok Leyland Stallion 4x4",
    eta: "3h 45m",
    activeSector: "Meghalaya Highlands",
    lat: 25.578,
    lng: 91.893,
    elevationMeters: 1520,
  },
  {
    id: "CV-02",
    callsign: "MED-ALPHA-02",
    category: "medical",
    agency: "Indian Red Cross",
    origin: "Jorhat Army Hospital",
    destination: "Mokokchung Relief Unit",
    cargoDesc: "Tetanus, Antibiotics & Trauma Splints",
    weightMT: 8.2,
    status: "en_route",
    corridor: "NH-702",
    vehicleType: "Tata LPTA 715",
    eta: "2h 10m",
    activeSector: "Nagaland Border",
    lat: 26.31,
    lng: 94.52,
    elevationMeters: 1320,
  },
  {
    id: "CV-03",
    callsign: "MED-ALPHA-03",
    category: "medical",
    agency: "Armed Forces Medical (AFMS)",
    origin: "Tezpur Military Base",
    destination: "Dirang Field Hospital",
    cargoDesc: "High Altitude Sickness Antidotes & Hyperbaric Bags",
    weightMT: 11.0,
    status: "en_route",
    corridor: "NH-13",
    vehicleType: "Mahindra Marksman Protected",
    eta: "1h 50m",
    activeSector: "West Kameng",
    lat: 27.264,
    lng: 92.423,
    elevationMeters: 2415,
  },
  {
    id: "CV-04",
    callsign: "MED-BRAVO-04",
    category: "medical",
    agency: "NDRF High-Altitude Unit",
    origin: "Tezpur Forward Logistics",
    destination: "Tawang District Hospital",
    cargoDesc: "Emergency Surgical Packs & Portable O2 Concentrators",
    weightMT: 14.5,
    status: "delayed",
    corridor: "NH-13",
    vehicleType: "Ashok Leyland 4x4 All-Terrain",
    eta: "HOLD (Landslide)",
    activeSector: "Bomdila-Sela Sector",
    lat: 27.32,
    lng: 92.35,
    impactedByHazard: "Landslide at Km 42 (NH-13 Tawang)",
    elevationMeters: 2415,
  },
  {
    id: "CV-05",
    callsign: "MED-CHARLIE-05",
    category: "medical",
    agency: "Assam Rifles Medical",
    origin: "Dimapur Logistics Base",
    destination: "Kohima Disaster Ward",
    cargoDesc: "Surgical Dressing & Waterborne Illness Packs",
    weightMT: 7.8,
    status: "en_route",
    corridor: "NH-29",
    vehicleType: "Tata 407 4x4 Ambulance",
    eta: "1h 15m",
    activeSector: "Chumukedima Pass",
    lat: 25.79,
    lng: 93.77,
    elevationMeters: 620,
  },
  {
    id: "CV-06",
    callsign: "MED-CHARLIE-06",
    category: "medical",
    agency: "NDRF 10th Bn",
    origin: "Kohima Depot",
    destination: "Imphal Kangla Camp",
    cargoDesc: "Anti-venom, IV Fluids & Burn Kits",
    weightMT: 10.4,
    status: "en_route",
    corridor: "NH-2",
    vehicleType: "BEML Tatra Heavy QRV",
    eta: "4h 20m",
    activeSector: "Mao Gate Inter-State Pass",
    lat: 25.5,
    lng: 94.15,
    elevationMeters: 1820,
  },
  {
    id: "CV-07",
    callsign: "MED-DELTA-07",
    category: "medical",
    agency: "Mizoram Health Mission",
    origin: "Silchar Supply Depot",
    destination: "Aizawl Civil Hospital",
    cargoDesc: "Dialysis Consumables & Emergency Injections",
    weightMT: 9.0,
    status: "en_route",
    corridor: "NH-306",
    vehicleType: "Swaraj Mazda 4x4",
    eta: "5h 10m",
    activeSector: "Kolasib Ridge",
    lat: 24.22,
    lng: 92.68,
    elevationMeters: 890,
  },
  {
    id: "CV-08",
    callsign: "MED-ECHO-08",
    category: "medical",
    agency: "Tripura Disaster Response",
    origin: "Agartala Central Yard",
    destination: "Dharmanagar Evac Center",
    cargoDesc: "Pediatric Antibiotics & ORS Sachets",
    weightMT: 6.5,
    status: "en_route",
    corridor: "NH-8",
    vehicleType: "Tata LPT 709",
    eta: "3h 05m",
    activeSector: "Teliamura Hills",
    lat: 23.83,
    lng: 91.64,
    elevationMeters: 110,
  },
  {
    id: "CV-10",
    callsign: "MED-FOXTROT-10",
    category: "medical",
    agency: "Sikkim Disaster Management",
    origin: "Siliguri Staging Hub",
    destination: "Gangtok Multi-Specialty",
    cargoDesc: "Cardiovascular Support & Blood Coolers",
    weightMT: 12.0,
    status: "en_route",
    corridor: "NH-10",
    vehicleType: "Ashok Leyland 4x4",
    eta: "2h 40m",
    activeSector: "Teesta Low Dam",
    lat: 27.05,
    lng: 88.52,
    elevationMeters: 650,
  },
  {
    id: "CV-11",
    callsign: "MED-GOLF-11",
    category: "medical",
    agency: "BRO Medical Support",
    origin: "Itanagar Base",
    destination: "Ziro Valley Medical Center",
    cargoDesc: "Hypothermia Blankets & Emergency Stretcher Units",
    weightMT: 8.5,
    status: "en_route",
    corridor: "NH-13 (East)",
    vehicleType: "Force Gurkha QRV",
    eta: "3h 15m",
    activeSector: "Yachuli Defile",
    lat: 27.48,
    lng: 93.81,
    elevationMeters: 1560,
  },
  {
    id: "CV-12",
    callsign: "MED-HOTEL-12",
    category: "medical",
    agency: "Meghalaya Health Dept",
    origin: "Guwahati Depot",
    destination: "Tura Civil Hospital",
    cargoDesc: "Maternal Health Kits & Antiseptic Stocks",
    weightMT: 9.8,
    status: "en_route",
    corridor: "NH-217",
    vehicleType: "Tata 407 4x4",
    eta: "4h 45m",
    activeSector: "Garo Hills Foothills",
    lat: 25.68,
    lng: 90.41,
    elevationMeters: 380,
  },
  {
    id: "CV-13",
    callsign: "MED-INDIA-13",
    category: "medical",
    agency: "NDRF Field Ambulance",
    origin: "Dibrugarh Railway Yard",
    destination: "Pasighat Emergency Point",
    cargoDesc: "Diagnostic Field Kits & Suture Packs",
    weightMT: 10.8,
    status: "en_route",
    corridor: "NH-515",
    vehicleType: "Ashok Leyland Stallion",
    eta: "2h 25m",
    activeSector: "Bogibeel Sector",
    lat: 27.75,
    lng: 95.12,
    elevationMeters: 140,
  },

  // Food & Rations Convoys (18)
  {
    id: "CV-14",
    callsign: "RATION-01",
    category: "food",
    agency: "Food Corporation of India (FCI)",
    origin: "Guwahati FCI Depot",
    destination: "Barpeta Flood Relief",
    cargoDesc: "Rice, Pulses, Iodized Salt & Milk Powder",
    weightMT: 24.0,
    status: "en_route",
    corridor: "NH-27",
    vehicleType: "BharatBenz 2823C Heavy Hauler",
    eta: "1h 30m",
    activeSector: "Kamrup Rural",
    lat: 26.24,
    lng: 91.31,
    elevationMeters: 48,
  },
  {
    id: "CV-15",
    callsign: "RATION-02",
    category: "food",
    agency: "FCI Assam",
    origin: "Tezpur Godown",
    destination: "Lakhimpur Inundated Villages",
    cargoDesc: "Fortified Rice & Edible Oils",
    weightMT: 22.0,
    status: "en_route",
    corridor: "NH-15",
    vehicleType: "Tata Signa 3523",
    eta: "3h 10m",
    activeSector: "Biswanath Chariali",
    lat: 26.74,
    lng: 93.15,
    elevationMeters: 78,
  },
  {
    id: "CV-16",
    callsign: "RATION-03",
    category: "food",
    agency: "PM POSHAN Disaster Relief",
    origin: "Dimapur Warehouse",
    destination: "Mon District Highland Communities",
    cargoDesc: "Nutritious High-Energy Biscuits & Rations",
    weightMT: 14.0,
    status: "en_route",
    corridor: "NH-702B",
    vehicleType: "Ashok Leyland Boss 1415",
    eta: "6h 15m",
    activeSector: "Naginimora Pass",
    lat: 26.85,
    lng: 94.95,
    elevationMeters: 890,
  },
  {
    id: "CV-17",
    callsign: "RATION-04",
    category: "food",
    agency: "WFP / Red Cross",
    origin: "Silchar Hub",
    destination: "Champhai Border Relief",
    cargoDesc: "Emergency Rations & Ready-to-Eat Packs",
    weightMT: 16.5,
    status: "en_route",
    corridor: "NH-6 (Mizoram)",
    vehicleType: "Tata LPTA 1618",
    eta: "7h 00m",
    activeSector: "Keifang Ridge",
    lat: 23.65,
    lng: 93.12,
    elevationMeters: 1420,
  },
  {
    id: "CV-18",
    callsign: "RATION-05",
    category: "food",
    agency: "NDRF Logistics",
    origin: "Guwahati FCI Depot",
    destination: "Dhubri Riverine Relief",
    cargoDesc: "Water Bottles (50,000L) & Flour Bags",
    weightMT: 18.0,
    status: "en_route",
    corridor: "NH-17",
    vehicleType: "Mahindra Blazo X 28",
    eta: "3h 40m",
    activeSector: "Goalpara Floodplain",
    lat: 26.17,
    lng: 90.62,
    elevationMeters: 42,
  },
  {
    id: "CV-19",
    callsign: "RATION-06",
    category: "food",
    agency: "Arunachal Food Dept",
    origin: "Bhalukpong Gate",
    destination: "Dirang Civil Supply",
    cargoDesc: "Wheat Grain, Lentils & Compressed Fuel Pellets",
    weightMT: 15.0,
    status: "en_route",
    corridor: "NH-13",
    vehicleType: "Ashok Leyland 4x4",
    eta: "4h 10m",
    activeSector: "Tenga Valley",
    lat: 27.18,
    lng: 92.52,
    elevationMeters: 1260,
  },
  {
    id: "CV-20",
    callsign: "RATION-07",
    category: "food",
    agency: "FCI Nagaland",
    origin: "Dimapur Railway Shed",
    destination: "Wokha Relief Center",
    cargoDesc: "Grain Sacks & Baby Nutrition Formula",
    weightMT: 13.5,
    status: "en_route",
    corridor: "NH-2",
    vehicleType: "Tata 1613 4x4",
    eta: "2h 45m",
    activeSector: "Doyang Dam Sector",
    lat: 26.15,
    lng: 94.22,
    elevationMeters: 960,
  },
  {
    id: "CV-21",
    callsign: "RATION-08",
    category: "food",
    agency: "Manipur Relief Taskforce",
    origin: "Imphal Kangla Hub",
    destination: "Churachandpur Evac Camp",
    cargoDesc: "Fortified Rice & Cooking Essentials",
    weightMT: 12.0,
    status: "en_route",
    corridor: "NH-102B",
    vehicleType: "Eicher Pro 3019",
    eta: "2h 00m",
    activeSector: "Bishnupur Defile",
    lat: 24.62,
    lng: 93.75,
    elevationMeters: 790,
  },
  {
    id: "CV-22",
    callsign: "RATION-09",
    category: "food",
    agency: "Meghalaya PDS",
    origin: "Shillong Civil Depot",
    destination: "Cherrapunji / Sohra Highland",
    cargoDesc: "Dry Food Rations & Water Filtration Tablets",
    weightMT: 11.2,
    status: "en_route",
    corridor: "SH-5",
    vehicleType: "Ashok Leyland Boss",
    eta: "1h 45m",
    activeSector: "East Khasi Hills",
    lat: 25.32,
    lng: 91.73,
    elevationMeters: 1480,
  },
  {
    id: "CV-23",
    callsign: "RATION-10",
    category: "food",
    agency: "Tripura Food Supply",
    origin: "Udaipur Godown",
    destination: "Sabroom Transit Shelter",
    cargoDesc: "Sugar, Dal, Salt & Instant Meal Sachets",
    weightMT: 10.5,
    status: "en_route",
    corridor: "NH-8",
    vehicleType: "Tata LPTA 1109",
    eta: "2h 15m",
    activeSector: "South Tripura",
    lat: 23.32,
    lng: 91.51,
    elevationMeters: 38,
  },
  {
    id: "CV-24",
    callsign: "RATION-11",
    category: "food",
    agency: "Sikkim Food Logistics",
    origin: "Jorethang Hub",
    destination: "Pelling High Altitude Village",
    cargoDesc: "Mountain Ration Barrels & Lentils",
    weightMT: 9.8,
    status: "en_route",
    corridor: "SH-8",
    vehicleType: "Mahindra Furio 12",
    eta: "3h 30m",
    activeSector: "West Sikkim",
    lat: 27.31,
    lng: 88.24,
    elevationMeters: 2150,
  },
  {
    id: "CV-25",
    callsign: "RATION-12",
    category: "food",
    agency: "FCI Assam",
    origin: "Nagaon Warehouse",
    destination: "Morigaon Flood Relief",
    cargoDesc: "Drinking Water Tankers & Dry Rations",
    weightMT: 17.5,
    status: "en_route",
    corridor: "NH-715A",
    vehicleType: "BharatBenz 1923C",
    eta: "1h 10m",
    activeSector: "Brahmaputra South Bank",
    lat: 26.35,
    lng: 92.51,
    elevationMeters: 55,
  },
  {
    id: "CV-26",
    callsign: "RATION-13",
    category: "food",
    agency: "NDRF Eastern Sector",
    origin: "Tezpur Base",
    destination: "Dhemaji Flood Shelter",
    cargoDesc: "Emergency Rations & Inflatable Raft Bundles",
    weightMT: 15.0,
    status: "en_route",
    corridor: "NH-15",
    vehicleType: "Tata Signa 2823",
    eta: "4h 00m",
    activeSector: "Gogamukh Floodplain",
    lat: 27.52,
    lng: 94.41,
    elevationMeters: 85,
  },
  {
    id: "CV-27",
    callsign: "RATION-14",
    category: "food",
    agency: "Arunachal Disaster Authority",
    origin: "Pasighat Hub",
    destination: "Yingkiong Mountain Community",
    cargoDesc: "Mountain Rations & Salt Bricks",
    weightMT: 10.0,
    status: "en_route",
    corridor: "NH-513",
    vehicleType: "Ashok Leyland 4x4",
    eta: "5h 20m",
    activeSector: "Upper Siang Gorge",
    lat: 28.61,
    lng: 95.02,
    elevationMeters: 850,
  },
  {
    id: "CV-28",
    callsign: "RATION-15",
    category: "food",
    agency: "Meghalaya Relief Cell",
    origin: "Nongpoh Warehouse",
    destination: "Mairang Sub-division",
    cargoDesc: "Grain Bags & Clean Water Carboys",
    weightMT: 11.5,
    status: "en_route",
    corridor: "NH-106",
    vehicleType: "Tata LPT 1109",
    eta: "2h 30m",
    activeSector: "West Khasi Hills",
    lat: 25.56,
    lng: 91.64,
    elevationMeters: 1620,
  },
  {
    id: "CV-29",
    callsign: "RATION-16",
    category: "food",
    agency: "FCI Mizoram",
    origin: "Bairabi Railhead",
    destination: "Mamit Mountain Camp",
    cargoDesc: "Fortified Rice & Edible Oils",
    weightMT: 13.0,
    status: "en_route",
    corridor: "SH-3",
    vehicleType: "Mahindra Blazo 25",
    eta: "4h 50m",
    activeSector: "Dampa Tiger Reserve Boundary",
    lat: 23.91,
    lng: 92.48,
    elevationMeters: 780,
  },
  {
    id: "CV-30",
    callsign: "RATION-17",
    category: "food",
    agency: "Nagaland Civil Supplies",
    origin: "Kohima Depot",
    destination: "Phek Border Village",
    cargoDesc: "Cereals & High Energy Nutritional Paste",
    weightMT: 10.8,
    status: "en_route",
    corridor: "SH-14",
    vehicleType: "Tata 407 4x4",
    eta: "3h 40m",
    activeSector: "Chakhesang Ridge",
    lat: 25.68,
    lng: 94.49,
    elevationMeters: 1680,
  },
  {
    id: "CV-31",
    callsign: "RATION-18",
    category: "food",
    agency: "Manipur Relief Comm.",
    origin: "Imphal Kangla Depot",
    destination: "Ukhrul Highland Center",
    cargoDesc: "Ready-To-Eat MREs & Flour",
    weightMT: 9.7,
    status: "en_route",
    corridor: "NH-202",
    vehicleType: "Ashok Leyland Boss",
    eta: "3h 10m",
    activeSector: "Shirui Peak Foothills",
    lat: 25.11,
    lng: 94.36,
    elevationMeters: 1750,
  },

  // Fuel / POL Convoys (7)
  {
    id: "CV-09",
    callsign: "POL-TANKER-09",
    category: "fuel",
    agency: "Indian Oil Corp (IOCL)",
    origin: "Numaligarh Refinery (NRL)",
    destination: "Tawang Army Forward Fuel Depot",
    cargoDesc: "Aviation Fuel & High-Altitude Diesel (Arctic Grade)",
    weightMT: 32.0,
    status: "delayed",
    corridor: "NH-13",
    vehicleType: "Heavy Multi-Axle Fuel Tanker (6x6)",
    eta: "HOLD (Landslide)",
    activeSector: "Bomdila Pass Peak",
    lat: 27.264,
    lng: 92.423,
    impactedByHazard: "Landslide at Km 42 (NH-13 Tawang)",
    elevationMeters: 2415,
  },
  {
    id: "CV-32",
    callsign: "POL-TANKER-02",
    category: "fuel",
    agency: "IOCL Assam",
    origin: "Guwahati Refinery",
    destination: "Shillong Electricity Grid Generators",
    cargoDesc: "Heavy Diesel for Hospital Backups",
    weightMT: 28.0,
    status: "en_route",
    corridor: "NH-6",
    vehicleType: "BharatBenz 2823 TT Tanker",
    eta: "2h 15m",
    activeSector: "Umiam Corridor",
    lat: 25.68,
    lng: 91.90,
    elevationMeters: 1020,
  },
  {
    id: "CV-33",
    callsign: "POL-TANKER-03",
    category: "fuel",
    agency: "Bharat Petroleum (BPCL)",
    origin: "Digboi Refinery",
    destination: "Miao Forward Post (Arunachal)",
    cargoDesc: "High Grade Petrol & Kerosene for Relief Stoves",
    weightMT: 26.0,
    status: "en_route",
    corridor: "NH-215",
    vehicleType: "Tata Signa 3525.K Tanker",
    eta: "4h 30m",
    activeSector: "Tirap Border",
    lat: 27.48,
    lng: 95.91,
    elevationMeters: 210,
  },
  {
    id: "CV-34",
    callsign: "POL-TANKER-04",
    category: "fuel",
    agency: "Hindustan Petroleum (HPCL)",
    origin: "Silchar Depot",
    destination: "Aizawl Emergency Power Reserve",
    cargoDesc: "Low-Sulfur Diesel Fuel",
    weightMT: 25.0,
    status: "en_route",
    corridor: "NH-306",
    vehicleType: "Ashok Leyland 2820 Tanker",
    eta: "5h 40m",
    activeSector: "Dholai Valley",
    lat: 24.58,
    lng: 92.74,
    elevationMeters: 95,
  },
  {
    id: "CV-35",
    callsign: "POL-TANKER-05",
    category: "fuel",
    agency: "IOCL Dimapur",
    origin: "Dimapur Terminal",
    destination: "Imphal Kangla Power Generating Station",
    cargoDesc: "Critical Generator Diesel",
    weightMT: 30.0,
    status: "en_route",
    corridor: "NH-2",
    vehicleType: "BEML 6x6 Heavy Fuel Hauler",
    eta: "4h 50m",
    activeSector: "Kohima Valley Bypass",
    lat: 25.67,
    lng: 94.108,
    elevationMeters: 1444,
  },
  {
    id: "CV-36",
    callsign: "POL-TANKER-06",
    category: "fuel",
    agency: "IOCL Siliguri",
    origin: "Siliguri Staging Terminal",
    destination: "Gangtok Power Backup Plant",
    cargoDesc: "Arctic Kerosene & High-Flash Diesel",
    weightMT: 22.0,
    status: "en_route",
    corridor: "NH-10",
    vehicleType: "BharatBenz 2523 R",
    eta: "3h 15m",
    activeSector: "Rangpo Border Post",
    lat: 27.18,
    lng: 88.53,
    elevationMeters: 450,
  },
  {
    id: "CV-37",
    callsign: "POL-TANKER-07",
    category: "fuel",
    agency: "NRL Assam",
    origin: "Numaligarh Depot",
    destination: "Itanagar Government Fleet Depot",
    cargoDesc: "Diesel & Ethanol-Blended Fuel",
    weightMT: 17.0,
    status: "en_route",
    corridor: "NH-415",
    vehicleType: "Tata Signa 2823",
    eta: "2h 45m",
    activeSector: "Bandardewa Gate",
    lat: 27.10,
    lng: 93.62,
    elevationMeters: 320,
  },

  // Heavy Machinery / Excavators (5)
  {
    id: "CV-38",
    callsign: "BRO-HEAVY-01",
    category: "machinery",
    agency: "Border Roads Organisation (Project Vartak)",
    origin: "Tezpur BRO Base",
    destination: "Sela Pass Landslide Defile",
    cargoDesc: "Caterpillar Hydraulic Breakers & D8R Bulldozer",
    weightMT: 38.0,
    status: "en_route",
    corridor: "NH-13",
    vehicleType: "BEML Tatra 8x8 Low-Bed Trailer",
    eta: "3h 30m",
    activeSector: "Bomdila Pass Peak",
    lat: 27.264,
    lng: 92.423,
    elevationMeters: 2415,
  },
  {
    id: "CV-39",
    callsign: "BRO-HEAVY-02",
    category: "machinery",
    agency: "BRO (Project Pushpak)",
    origin: "Shillong Military Depot",
    destination: "Sonapur Mudslide Defile",
    cargoDesc: "Komatsu Wheel Loader & Heavy Winch Recoverer",
    weightMT: 18.0,
    status: "en_route",
    corridor: "NH-6",
    vehicleType: "Ashok Leyland 8x4 Heavy Hauler",
    eta: "1h 45m",
    activeSector: "Jowai Ridge",
    lat: 25.44,
    lng: 92.20,
    elevationMeters: 1380,
  },
  {
    id: "CV-40",
    callsign: "BRO-HEAVY-03",
    category: "machinery",
    agency: "BRO (Project Sewak)",
    origin: "Dimapur Heavy Equipment Depot",
    destination: "Mao Gate Slump Clearing",
    cargoDesc: "JCB 3DX Super Excavator & Rock Crusher Unit",
    weightMT: 14.0,
    status: "en_route",
    corridor: "NH-2",
    vehicleType: "Tata Prima 3530.K",
    eta: "2h 50m",
    activeSector: "Kohima Highland Command",
    lat: 25.67,
    lng: 94.108,
    elevationMeters: 1444,
  },
  {
    id: "CV-41",
    callsign: "BRO-HEAVY-04",
    category: "machinery",
    agency: "BRO (Project Brahmank)",
    origin: "Pasighat Workshop",
    destination: "Roing Mountain Defile",
    cargoDesc: "Hitachi Tracked Excavator & Soil Nailing Rig",
    weightMT: 12.0,
    status: "en_route",
    corridor: "NH-513",
    vehicleType: "Mahindra Blazo 40 Lowbed",
    eta: "3h 10m",
    activeSector: "Dibang River Basin",
    lat: 28.14,
    lng: 95.84,
    elevationMeters: 390,
  },
  {
    id: "CV-42",
    callsign: "BRO-HEAVY-05",
    category: "machinery",
    agency: "BRO (Project Swastik)",
    origin: "Siliguri Heavy Depot",
    destination: "Singtam Teesta Breach Wall",
    cargoDesc: "Volvo High-Reach Demolition & Shoring Equipment",
    weightMT: 8.0,
    status: "en_route",
    corridor: "NH-10",
    vehicleType: "BEML Tatra 6x6 Heavy",
    eta: "2h 15m",
    activeSector: "Sevoke Road Sector",
    lat: 26.89,
    lng: 88.47,
    elevationMeters: 180,
  },
];

